import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

function Footer() {
  const year = new Date().getFullYear();
  return <footer>Copyright © QueKiwi {year}</footer>;
}

function Header() {
  return (
    <header>
      <nav>
        <ul>
          <li>
            <Link href="">Inicio</Link>
          </li>
          <li>
            <Link href="nosotros">Nosotros</Link>
          </li>
          <li>
            <Link href="contactenos">Contactenos</Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}
